# Generated by Django 3.1.1 on 2020-09-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200916_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'BTS', 'verbose_name_plural': 'BTS'},
        ),
    ]
